# Generated by Django 4.2.2 on 2023-07-12 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airlinename', models.CharField(blank=True, db_column='AirlineName', max_length=100, null=True)),
                ('licenseno', models.IntegerField(db_column='LicenseNo', primary_key=True, serialize=False)),
                ('registeredcountry', models.CharField(blank=True, db_column='RegisteredCountry', max_length=50, null=True)),
            ],
            options={
                'db_table': 'airlines',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('airplaneid', models.IntegerField(db_column='AirplaneID', primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
                ('fuel', models.DecimalField(blank=True, db_column='Fuel', decimal_places=2, max_digits=10, null=True)),
                ('registrationno', models.CharField(db_column='RegistrationNo', max_length=50)),
                ('modelno', models.CharField(blank=True, db_column='ModelNo', max_length=50, null=True)),
            ],
            options={
                'db_table': 'airplane',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airportcode', models.CharField(db_column='AirportCode', max_length=10, primary_key=True, serialize=False)),
                ('contactinfo', models.CharField(blank=True, db_column='ContactInfo', max_length=100, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=100, null=True)),
                ('portname', models.CharField(blank=True, db_column='PortName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'airport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightno', models.CharField(db_column='FlightNo', max_length=100, primary_key=True, serialize=False)),
                ('arrivaldate', models.DateField(blank=True, db_column='ArrivalDate', null=True)),
                ('arrivaltime', models.TimeField(blank=True, db_column='ArrivalTime', null=True)),
                ('departuretime', models.TimeField(blank=True, db_column='DepartureTime', null=True)),
                ('departuredate', models.DateField(blank=True, db_column='DepartureDate', null=True)),
                ('destination', models.CharField(blank=True, db_column='Destination', max_length=100, null=True)),
                ('departure', models.CharField(blank=True, db_column='Departure', max_length=100, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
            ],
            options={
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('luggageno', models.IntegerField(db_column='LuggageNo', primary_key=True, serialize=False)),
                ('noofbags', models.IntegerField(blank=True, db_column='NoOfBags', null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
            ],
            options={
                'db_table': 'luggage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.IntegerField(db_column='PersonId', primary_key=True, serialize=False)),
                ('phoneno', models.CharField(blank=True, db_column='PhoneNo', max_length=20, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=10, null=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, db_column='Lastname', max_length=50, null=True)),
                ('middlename', models.CharField(blank=True, db_column='Middlename', max_length=50, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationno', models.AutoField(db_column='ReservationNo', primary_key=True, serialize=False)),
                ('totalcost', models.DecimalField(blank=True, db_column='TotalCost', decimal_places=2, max_digits=10, null=True)),
                ('reservationdate', models.DateField(blank=True, db_column='ReservationDate', null=True)),
                ('bookingstatus', models.CharField(blank=True, db_column='BookingStatus', max_length=50, null=True)),
                ('flightno', models.ForeignKey(blank=True, db_column='FlightNo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.flight')),
            ],
            options={
                'db_table': 'reservation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketno', models.AutoField(db_column='TicketNo', primary_key=True, serialize=False)),
                ('seatno', models.CharField(blank=True, db_column='SeatNo', max_length=10, null=True)),
                ('fare', models.DecimalField(blank=True, db_column='Fare', decimal_places=2, max_digits=10, null=True)),
                ('flightno', models.ForeignKey(blank=True, db_column='Flightno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.flight')),
                ('personid', models.OneToOneField(db_column='PersonId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.person')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('job', models.CharField(blank=True, db_column='Job', max_length=50, null=True)),
                ('qualification', models.CharField(blank=True, db_column='Qualification', max_length=50, null=True)),
                ('salary', models.DecimalField(blank=True, db_column='Salary', decimal_places=2, max_digits=10, null=True)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('personid', models.OneToOneField(db_column='PersonId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.person')),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reside',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('airplaneid', models.OneToOneField(db_column='AirplaneId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.airplane')),
                ('airportcode', models.ForeignKey(db_column='AirportCode', on_delete=django.db.models.deletion.DO_NOTHING, to='home.airport')),
            ],
            options={
                'db_table': 'reside',
                'managed': True,
                'unique_together': {('airplaneid', 'airportcode')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reservationno', models.ForeignKey(db_column='ReservationNo', on_delete=django.db.models.deletion.DO_NOTHING, to='home.reservation')),
            ],
            options={
                'db_table': 'booking',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='airplane',
            name='Airports',
            field=models.ManyToManyField(through='home.Reside', to='home.airport'),
        ),
        migrations.CreateModel(
            name='ReservedTicket',
            fields=[
                ('ticketno', models.OneToOneField(db_column='TicketNo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.ticket')),
                ('reservationno', models.ForeignKey(blank=True, db_column='ReservationNo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.reservation')),
            ],
            options={
                'db_table': 'reservedtickets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReservedFlight',
            fields=[
                ('reservationno', models.OneToOneField(db_column='ReservationNo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.reservation')),
                ('flightno', models.ForeignKey(blank=True, db_column='FlightNo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.flight')),
            ],
            options={
                'db_table': 'reservedflight',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PassengerCount',
            fields=[
                ('reservationno', models.OneToOneField(db_column='ReservationNo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.reservation')),
                ('age', models.IntegerField(db_column='Age')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'passengercount',
                'managed': True,
                'unique_together': {('reservationno', 'age', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('personid', models.OneToOneField(db_column='PersonId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.person')),
                ('passportno', models.CharField(blank=True, db_column='PassportNo', max_length=20, null=True)),
                ('flightno', models.ForeignKey(blank=True, db_column='FlightNo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.flight')),
                ('reservation', models.ManyToManyField(through='home.Booking', to='home.reservation')),
                ('ticketno', models.ForeignKey(blank=True, db_column='TicketNo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.ticket')),
            ],
            options={
                'db_table': 'passenger',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FlightAssignment',
            fields=[
                ('flightno', models.OneToOneField(db_column='FlightNo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.flight')),
                ('airplaneid', models.ForeignKey(db_column='AirplaneId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.airplane')),
            ],
            options={
                'db_table': 'flightassignment',
                'managed': True,
                'unique_together': {('airplaneid', 'flightno')},
            },
        ),
        migrations.CreateModel(
            name='FinancialManagement',
            fields=[
                ('licenseno', models.OneToOneField(db_column='LicenseNo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.airline')),
                ('revenue', models.DecimalField(db_column='Revenue', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'financialmanagement',
                'managed': True,
                'unique_together': {('revenue', 'licenseno')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='personid',
            field=models.ForeignKey(db_column='PersonId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.passenger'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='flights',
            field=models.ManyToManyField(through='home.FlightAssignment', to='home.flight'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('licenseno', models.OneToOneField(db_column='LicenseNo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.airline')),
                ('personid', models.ForeignKey(db_column='PersonId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.person')),
            ],
            options={
                'db_table': 'works',
                'managed': True,
                'unique_together': {('licenseno', 'personid')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('reservationno', 'personid')},
        ),
        migrations.CreateModel(
            name='Belonging',
            fields=[
                ('luggageno', models.OneToOneField(db_column='LuggageNo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.luggage')),
                ('personid', models.ForeignKey(db_column='PersonId', on_delete=django.db.models.deletion.DO_NOTHING, to='home.person')),
            ],
            options={
                'db_table': 'belonging',
                'managed': True,
                'unique_together': {('luggageno', 'personid')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='airplane',
            unique_together={('airplaneid', 'registrationno')},
        ),
        migrations.CreateModel(
            name='Airline_Flight',
            fields=[
                ('flightno', models.OneToOneField(db_column='FlightNo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.flight')),
                ('licenseno', models.ForeignKey(db_column='LicenseNo', on_delete=django.db.models.deletion.DO_NOTHING, to='home.airline')),
            ],
            options={
                'db_table': 'airline_flight',
                'managed': True,
                'unique_together': {('licenseno', 'flightno')},
            },
        ),
    ]
