# Generated by Django 4.2.2 on 2023-07-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='luggage',
            options={},
        ),
        migrations.AlterField(
            model_name='luggage',
            name='luggageno',
            field=models.AutoField(db_column='LuggageNo', primary_key=True, serialize=False),
        ),
    ]
